[2024-12-14 11:13:21] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 11:13:21] [INFO   ] discord.client: logging in using static token
[2024-12-14 11:13:21] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4c3ff53942f035b08ad579cc4624b1e0).
[2024-12-14 11:13:23] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 11:39:45] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 11:39:45] [INFO   ] discord.client: logging in using static token
[2024-12-14 11:39:46] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1eb9c668521f8ce9446b235bc002d47c).
[2024-12-14 11:39:48] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 11:40:27] [ERROR  ] racbot: In iisr permban:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\roblox.py", line 93, in iisr_perm_ban
    async with self.bot.session.post(
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 728, in _request
    await resp.start(conn)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\streams.py", line 667, in read
    await self._waiter
aiohttp.client_exceptions.SocketTimeoutError: Timeout on reading data from socket
[2024-12-14 11:42:05] [ERROR  ] racbot: In iisr permban:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\roblox.py", line 93, in iisr_perm_ban
    async with self.bot.session.post(
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 728, in _request
    await resp.start(conn)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\streams.py", line 667, in read
    await self._waiter
aiohttp.client_exceptions.SocketTimeoutError: Timeout on reading data from socket
[2024-12-14 11:44:46] [ERROR  ] racbot: In iisr tempban:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\roblox.py", line 61, in iisr_temp_ban
    async with self.bot.session.post(
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 728, in _request
    await resp.start(conn)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\streams.py", line 667, in read
    await self._waiter
aiohttp.client_exceptions.SocketTimeoutError: Timeout on reading data from socket
[2024-12-14 11:46:30] [ERROR  ] racbot: In ping api:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\utility.py", line 34, in ping_api
    async with self.bot.session.get(Endpoints.UTILITY_PING.value, headers=api_headers) as resp:
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 728, in _request
    await resp.start(conn)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\streams.py", line 667, in read
    await self._waiter
aiohttp.client_exceptions.SocketTimeoutError: Timeout on reading data from socket
[2024-12-14 11:47:50] [ERROR  ] racbot: In ping api:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\utility.py", line 34, in ping_api
    async with self.bot.session.get(Endpoints.UTILITY_PING.value, headers=api_headers) as resp:
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client.py", line 728, in _request
    await resp.start(conn)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\aiohttp\streams.py", line 667, in read
    await self._waiter
aiohttp.client_exceptions.SocketTimeoutError: Timeout on reading data from socket
[2024-12-14 11:56:15] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 11:56:15] [INFO   ] discord.client: logging in using static token
[2024-12-14 11:56:16] [ERROR  ] racbot: failed to load extension cogs.utility
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 963, in _load_from_module_spec
    await setup(self)
  File "c:\Repositories\RAC-Bot\src\bot\cogs\utility.py", line 68, in setup
    await bot.add_cog(Utility(bot))
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 799, in add_cog
    cog = await cog._inject(self, override=override, guild=guild, guilds=guilds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\cog.py", line 725, in _inject
    raise e
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\cog.py", line 716, in _inject
    bot.add_command(command)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 253, in add_command
    super().add_command(command)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 1356, in add_command
    raise CommandRegistrationError(command.name)
discord.ext.commands.errors.CommandRegistrationError: The command invite is already an existing command or alias.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Repositories\RAC-Bot\src\bot\racbot.py", line 113, in setup_hook
    await self.load_extension(extension)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 1029, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\bot.py", line 968, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.utility' raised an error: CommandRegistrationError: The command invite is already an existing command or alias.
[2024-12-14 11:56:16] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2828cb8ec9a7955983a198a00664e7c1).
[2024-12-14 11:56:18] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 11:57:33] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 11:57:33] [INFO   ] discord.client: logging in using static token
[2024-12-14 11:57:34] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e95e66c65f932f2c3566ef2c60fcc060).
[2024-12-14 11:57:36] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 20:10:14] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 20:10:14] [INFO   ] discord.client: logging in using static token
[2024-12-14 20:10:15] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8939f9d843763259edc4b27b7a779485).
[2024-12-14 20:10:17] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 20:16:52] [ERROR  ] racbot: In iisr permban:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\roblox.py", line 126, in iisr_perm_ban
    'server_id': flags.server_id,
                 ^^^^^^^^^^^^^^^
AttributeError: 'IISRPermBanFlags' object has no attribute 'server_id'
[2024-12-14 20:16:58] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 20:16:58] [INFO   ] discord.client: logging in using static token
[2024-12-14 20:16:59] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 1496fb5c7c944f65517dc2ae7ec15bcf).
[2024-12-14 20:17:01] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 20:17:44] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 20:17:44] [INFO   ] discord.client: logging in using static token
[2024-12-14 20:17:45] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9c864fa6c86685a01e1c341ab5d51889).
[2024-12-14 20:17:47] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 20:19:56] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 20:19:56] [INFO   ] discord.client: logging in using static token
[2024-12-14 20:19:56] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bc44d961c5239f0cecbc9c91daf98ddc).
[2024-12-14 20:19:58] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 20:30:02] [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
[2024-12-14 20:30:02] [INFO   ] discord.client: logging in using static token
[2024-12-14 20:30:03] [INFO   ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d0dcd6c2b9085e06a799d264fd2d90e8).
[2024-12-14 20:30:05] [INFO   ] racbot: Ready: RAC#8732 (ID: 1221491594516103188)
[2024-12-14 20:34:59] [ERROR  ] racbot: In gemini:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\ai.py", line 60, in gemini
    response: str = JSON.loads(body).get('response')
                    ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2024-12-14 20:35:19] [ERROR  ] racbot: In gemini:
Traceback (most recent call last):
  File "C:\Repositories\RAC-Bot\venv\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Repositories\RAC-Bot\src\bot\cogs\ai.py", line 60, in gemini
    response: str = JSON.loads(str(body)).get('response')
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
